# Generated by Django 5.0.7 on 2024-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlist',
            old_name='name',
            new_name='title',
        ),
    ]
